### ISSUE TITLE
cannot convert from 'int' to 'Game.Constants.OverlayType'

### ISSUE THREAD

**Issue by mattdufeu** [kodolinija/stardeus-mod-template#5]
I just tried this template on v0.9.22 and I get the above error here https://github.com/kodolinija/stardeus-mod-template/blob/3cfde3178f1ce2a197bb0670de0bcef4b0f91381/Code/ExampleModSys.cs#L56

There isn't a 20 in the `OverlayType` enum, but I tried `OverlayType.Controls` and it seems "ok". Which one should we use?

**Comment by spajus** [comment]
OverlayInfo signature has changed recently, I didn't update the mod template yet, thanks for bringing it up. The first parameter used to be something like `int sortOrder`, now it's `OverlayType type`, which is an enum:

```
    public enum OverlayType : byte {
        Visual, // Oxygen, Heat, Rooms
        Information, // Resources, Beings, Quests, Goals, etc
        Special, // starmap, research, codex
        Controls, // terraforming, security, combat, expeditions
    }
```
I'll close this issue after the template is updated.

As for which one to use, pick the group that correlates the most with the other overlay buttons of that type.
